import { StyleSheet } from "react-native";
import { screenHeight, screenWidth } from "@/constants/Common";
import { Colors } from "@/constants/Colors";
const {
  lineColor,
  lightBlue,
  background,
  text,
  buttonBorder,
  textInputBorder,
  orTextColor,
} = Colors.light;

export const styles = StyleSheet.create({
  loginContainer: {
    flex: 1,
    backgroundColor: background,
    justifyContent: "center",
    alignItems: "center",
  },
  commonTextInput: {
    borderColor: textInputBorder,
    height: 40,
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: "top",
  },
  signUpContainer: {
    borderColor: buttonBorder,
    borderWidth: 1,
    borderRadius: 7,
    marginBottom: 80,
  },
  signUpText: {
    color: background,
    fontSize: 19,
    fontWeight: "700",
    paddingHorizontal: 70,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
    marginBottom: 80,
  },
  line: {
    backgroundColor: lineColor,
    width: "20%",
    height: 2,
    marginHorizontal: 10,
  },
  textInputMainView: {
    width: screenWidth * 0.8,
  },
  text: {
    color: orTextColor,
    fontSize: 19,
    fontWeight: "400",
  },
  textWhite: {
    color: background,
    fontSize: 16,
    fontWeight: "regular",
  },
  loginButtonContainer: {
    borderColor: buttonBorder,
    borderWidth: 1,
    borderRadius: 7,
    marginTop: 20,
  },
  createPostContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: screenHeight * 0.2,
  },
  createAccountContainer: {
    marginBottom: 40,
  },
  createAccountText: {
    color: lightBlue,
    fontSize: 35,
    fontWeight: "bold",
    paddingHorizontal: 50,
    paddingVertical: 10,
    textAlign: "center",
    justifyContent: "center",
  },
  createAccountButton: {
    borderColor: buttonBorder,
    borderRadius: 7,
    borderWidth: 1,
    marginTop: 20,
  },
  createAccountCta: {
    color: background,
    fontSize: 19,
    fontWeight: "700",
    paddingHorizontal: 70,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  mainContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    marginTop: screenHeight * 0.1,
  },
  newPostContainer: {
    borderColor: lightBlue,
    borderWidth: 2,
    marginBottom: screenHeight * 0.15,
    width: screenWidth - 20,
    alignSelf: "center",
  },
  newPostInsideContainer: {
    borderColor: lightBlue,
    borderWidth: 2,
    marginBottom: 40,
    paddingBottom: 10,
    width: screenWidth * 0.83,
    alignSelf: "center",
  },
  newPostText: {
    color: lightBlue,
    fontSize: 35,
    fontWeight: "700",
    paddingHorizontal: 50,
    paddingVertical: 10,
    justifyContent: "center",
    alignSelf: "center",
  },
  newPostInsideText: {
    color: text,
    fontSize: 19,
    fontWeight: "400",
    paddingHorizontal: 15,
    paddingVertical: 5,
    justifyContent: "center",
  },
  postAccountCta: {
    color: background,
    fontSize: 19,
    fontWeight: "700",
    alignItems: "center",
    justifyContent: "center",
  },
  postMessageButton: {
    borderColor: buttonBorder,
    borderWidth: 1,
    borderRadius: 7,
    marginTop: 5,
  },
  textInputCreate: { marginBottom: 40 },
  loginButton: {
    color: text,
  },
  textBoxBig: { height: 110 },
  gradient: {
    borderRadius: 6,
    overflow: "hidden",
  },
  imageContainer: {
    textAlign: "center",
    height: 100,
    width: 100,
    borderRadius: 10,
  },
  centerImage: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  selectImage: {
    position: "absolute",
    right: 10,
    bottom: 15,
    backgroundColor: lightBlue,
    padding: 5,
    borderRadius: 10,
  },
  postButton: {
    height: 40,
    width: 100,
    alignItems: "center",
    justifyContent: "center",
  }
});
